/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as AppsSlugRouteImport } from './routes/apps/$slug'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as ApiTwilioGatherRouteImport } from './routes/api/twilio/gather'
import { Route as ApiTwilioStatusRouteImport } from './routes/api/twilio/status'
import { Route as AppsAetherCraftRouteImport } from './routes/apps/aether/craft'
import { Route as AppsAetherSeeRouteImport } from './routes/apps/aether/see'
import { Route as AppsAetherVerifyRouteImport } from './routes/apps/aether/verify'
import { Route as AppsEmptyStretchPlayRouteImport } from './routes/apps/empty-stretch/play'
import { Route as AppsLookoutPlayRouteImport } from './routes/apps/lookout/play'
import { Route as AppsFieldvaultPlayRouteImport } from './routes/apps/fieldvault/play'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsSlugRoute = AppsSlugRouteImport.update({
  id: '/apps/$slug',
  path: '/apps/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwilioGatherRoute = ApiTwilioGatherRouteImport.update({
  id: '/api/twilio/gather',
  path: '/api/twilio/gather',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwilioStatusRoute = ApiTwilioStatusRouteImport.update({
  id: '/api/twilio/status',
  path: '/api/twilio/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAetherCraftRoute = AppsAetherCraftRouteImport.update({
  id: '/apps/aether/craft',
  path: '/apps/aether/craft',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAetherSeeRoute = AppsAetherSeeRouteImport.update({
  id: '/apps/aether/see',
  path: '/apps/aether/see',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAetherVerifyRoute = AppsAetherVerifyRouteImport.update({
  id: '/apps/aether/verify',
  path: '/apps/aether/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsEmptyStretchPlayRoute = AppsEmptyStretchPlayRouteImport.update({
  id: '/apps/empty-stretch/play',
  path: '/apps/empty-stretch/play',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsLookoutPlayRoute = AppsLookoutPlayRouteImport.update({
  id: '/apps/lookout/play',
  path: '/apps/lookout/play',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsFieldvaultPlayRoute = AppsFieldvaultPlayRouteImport.update({
  id: '/apps/fieldvault/play',
  path: '/apps/fieldvault/play',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coming-soon': typeof ComingSoonRoute
  '/api/rtc': typeof ApiRtcRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/apps/': typeof AppsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/twilio/gather': typeof ApiTwilioGatherRoute
  '/api/twilio/status': typeof ApiTwilioStatusRoute
  '/apps/aether/craft': typeof AppsAetherCraftRoute
  '/apps/aether/see': typeof AppsAetherSeeRoute
  '/apps/aether/verify': typeof AppsAetherVerifyRoute
  '/apps/empty-stretch/play': typeof AppsEmptyStretchPlayRoute
  '/apps/lookout/play': typeof AppsLookoutPlayRoute
  '/apps/fieldvault/play': typeof AppsFieldvaultPlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coming-soon': typeof ComingSoonRoute
  '/api/rtc': typeof ApiRtcRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/apps': typeof AppsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/api/twilio/gather': typeof ApiTwilioGatherRoute
  '/api/twilio/status': typeof ApiTwilioStatusRoute
  '/apps/aether/craft': typeof AppsAetherCraftRoute
  '/apps/aether/see': typeof AppsAetherSeeRoute
  '/apps/aether/verify': typeof AppsAetherVerifyRoute
  '/apps/empty-stretch/play': typeof AppsEmptyStretchPlayRoute
  '/apps/lookout/play': typeof AppsLookoutPlayRoute
  '/apps/fieldvault/play': typeof AppsFieldvaultPlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coming-soon': typeof ComingSoonRoute
  '/api/rtc': typeof ApiRtcRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/apps/': typeof AppsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/twilio/gather': typeof ApiTwilioGatherRoute
  '/api/twilio/status': typeof ApiTwilioStatusRoute
  '/apps/aether/craft': typeof AppsAetherCraftRoute
  '/apps/aether/see': typeof AppsAetherSeeRoute
  '/apps/aether/verify': typeof AppsAetherVerifyRoute
  '/apps/empty-stretch/play': typeof AppsEmptyStretchPlayRoute
  '/apps/lookout/play': typeof AppsLookoutPlayRoute
  '/apps/fieldvault/play': typeof AppsFieldvaultPlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coming-soon'
    | '/api/rtc'
    | '/apps/$slug'
    | '/projects/$slug'
    | '/apps/'
    | '/projects/'
    | '/api/twilio/gather'
    | '/api/twilio/status'
    | '/apps/aether/craft'
    | '/apps/aether/see'
    | '/apps/aether/verify'
    | '/apps/empty-stretch/play'
    | '/apps/lookout/play'
    | '/apps/fieldvault/play'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coming-soon'
    | '/api/rtc'
    | '/apps/$slug'
    | '/projects/$slug'
    | '/apps'
    | '/projects'
    | '/api/twilio/gather'
    | '/api/twilio/status'
    | '/apps/aether/craft'
    | '/apps/aether/see'
    | '/apps/aether/verify'
    | '/apps/empty-stretch/play'
    | '/apps/lookout/play'
    | '/apps/fieldvault/play'
  id:
    | '__root__'
    | '/'
    | '/coming-soon'
    | '/api/rtc'
    | '/apps/$slug'
    | '/projects/$slug'
    | '/apps/'
    | '/projects/'
    | '/api/twilio/gather'
    | '/api/twilio/status'
    | '/apps/aether/craft'
    | '/apps/aether/see'
    | '/apps/aether/verify'
    | '/apps/empty-stretch/play'
    | '/apps/lookout/play'
    | '/apps/fieldvault/play'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComingSoonRoute: typeof ComingSoonRoute
  ApiRtcRoute: typeof ApiRtcRoute
  AppsSlugRoute: typeof AppsSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  AppsIndexRoute: typeof AppsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiTwilioGatherRoute: typeof ApiTwilioGatherRoute
  ApiTwilioStatusRoute: typeof ApiTwilioStatusRoute
  AppsAetherCraftRoute: typeof AppsAetherCraftRoute
  AppsAetherSeeRoute: typeof AppsAetherSeeRoute
  AppsAetherVerifyRoute: typeof AppsAetherVerifyRoute
  AppsEmptyStretchPlayRoute: typeof AppsEmptyStretchPlayRoute
  AppsLookoutPlayRoute: typeof AppsLookoutPlayRoute
  AppsFieldvaultPlayRoute: typeof AppsFieldvaultPlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$slug': {
      id: '/apps/$slug'
      path: '/apps/$slug'
      fullPath: '/apps/$slug'
      preLoaderRoute: typeof AppsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twilio/gather': {
      id: '/api/twilio/gather'
      path: '/api/twilio/gather'
      fullPath: '/api/twilio/gather'
      preLoaderRoute: typeof ApiTwilioGatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twilio/status': {
      id: '/api/twilio/status'
      path: '/api/twilio/status'
      fullPath: '/api/twilio/status'
      preLoaderRoute: typeof ApiTwilioStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/aether/craft': {
      id: '/apps/aether/craft'
      path: '/apps/aether/craft'
      fullPath: '/apps/aether/craft'
      preLoaderRoute: typeof AppsAetherCraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/aether/see': {
      id: '/apps/aether/see'
      path: '/apps/aether/see'
      fullPath: '/apps/aether/see'
      preLoaderRoute: typeof AppsAetherSeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/aether/verify': {
      id: '/apps/aether/verify'
      path: '/apps/aether/verify'
      fullPath: '/apps/aether/verify'
      preLoaderRoute: typeof AppsAetherVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/empty-stretch/play': {
      id: '/apps/empty-stretch/play'
      path: '/apps/empty-stretch/play'
      fullPath: '/apps/empty-stretch/play'
      preLoaderRoute: typeof AppsEmptyStretchPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/lookout/play': {
      id: '/apps/lookout/play'
      path: '/apps/lookout/play'
      fullPath: '/apps/lookout/play'
      preLoaderRoute: typeof AppsLookoutPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/fieldvault/play': {
      id: '/apps/fieldvault/play'
      path: '/apps/fieldvault/play'
      fullPath: '/apps/fieldvault/play'
      preLoaderRoute: typeof AppsFieldvaultPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComingSoonRoute: ComingSoonRoute,
  ApiRtcRoute: ApiRtcRoute,
  AppsSlugRoute: AppsSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  AppsIndexRoute: AppsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiTwilioGatherRoute: ApiTwilioGatherRoute,
  ApiTwilioStatusRoute: ApiTwilioStatusRoute,
  AppsAetherCraftRoute: AppsAetherCraftRoute,
  AppsAetherSeeRoute: AppsAetherSeeRoute,
  AppsAetherVerifyRoute: AppsAetherVerifyRoute,
  AppsEmptyStretchPlayRoute: AppsEmptyStretchPlayRoute,
  AppsLookoutPlayRoute: AppsLookoutPlayRoute,
  AppsFieldvaultPlayRoute: AppsFieldvaultPlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
